# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
           submodules: recursive

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: cd ${GITHUB_WORKSPACE} && ./release.sh nightly

